; [mapname:races]
; [mapname:teleports]
; [mapname:triggers]
; Формат для races/teleports: NameInMenu = targetname
; Формат для triggers: key = value
; triggers keys:
; races = info_teleport_destination
; teleports = info_target
; finish_fail_class = trigger_multiple
; block_class = func_wall
; finish_prefix = finish_
; fail_prefix = fail_
;
; Пример:
; [my_map:triggers]
; races = info_teleport_destination
; teleports = info_target
; finish_fail_class = trigger_multiple
; block_class = func_wall
; finish_prefix = finish_
; fail_prefix = fail_

; === ka_cshns1 ===
[ka_cshns1:races]
fastrun    	 = start_04
de_nuke ramp = start_03

[ka_cshns1:teleports]
lj room     = lj_rom

[ka_cshns1:triggers]
races = info_teleport_destination
teleports = info_target
finish_fail_class = trigger_multiple
block_class = func_wall
finish_prefix = finish_
fail_prefix = fail_
; === ka_cshns1 ===

; === hnsru_valkyrie-end ===
[hnsru_valkyrie-end:races]
fastrun 	= start_05
go_fastrun  = start_04
de_nuke     = start_01
notkz_namek = start_02
mls_illusionary = start_03
slide 		= Start_06

[hnsru_valkyrie-end:teleports]
lj room     = lj

[hnsru_valkyrie-end:triggers]
races = info_teleport_destination
teleports = info_target
finish_fail_class = trigger_multiple
block_class = func_wall
finish_prefix = finish_
fail_prefix = fail_
; === hnsru_valkyrie-end ===

; === ka_bomj1 ===
[ka_bomj1:races]
goldbhop 	= goldbhop
kz_green    = godliker2

[ka_bomj1:teleports]
lj room     = longjump1

[ka_bomj1:triggers]
races = info_teleport_destination
teleports = info_target
finish_fail_class = trigger_multiple
block_class = func_wall
finish_prefix = finish_
fail_prefix = fail_
; === ka_bomj1 ===

; === ka_anarchy1 ===
[ka_anarchy1:teleports]
lj room = lj

[ka_anarchy1:triggers]
races = info_teleport_destination
teleports = info_target
finish_fail_class = trigger_multiple
block_class = func_wall
finish_prefix = finish_
fail_prefix = fail_
; === ka_anarchy1 ===
